// Importações centralizadas de ícones do Lucide React
import { 
  ChevronLeft, 
  ChevronRight,
  Search,
  User,
  LogOut,
  Menu,
  X,
  Home,
  Briefcase,
  Settings,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Star,
  Heart,
  Share2,
  Edit,
  Trash2,
  Plus,
  Minus,
  Check,
  AlertCircle,
  Info,
  Filter,
  Grid,
  List,
  Eye,
  EyeOff,
  Upload,
  Download,
  ArrowLeft,
  ArrowRight,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  MessageCircle,
  Bell,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Package,
  Users,
  Building,
  Clipboard,
  FileText,
  Image as ImageIcon,
  Camera,
  Video,
  Music,
  Scissors,
  Wrench,
  Hammer,
  PaintBucket,
  Shirt,
  Coffee,
  Pizza,
  Car,
  Bike,
  Home as HomeIcon,
  Stethoscope,
  Dumbbell,
  Book,
  GraduationCap,
  Laptop,
  Smartphone,
  Wifi,
  Zap,
  Award,
  Target,
  TrendingUp,
  BarChart,
  PieChart,
  Bookmark,
  Flag,
  Tag,
  Percent,
  Globe,
  Link,
  Lock,
  Unlock,
  Shield,
  AlertTriangle,
  HelpCircle,
  Loader,
  RefreshCw,
  RotateCw,
  Save,
  Send,
  Copy,
  Clipboard as ClipboardIcon,
  Printer,
  Share,
  ThumbsUp,
  ThumbsDown,
  MessageSquare,
  AtSign,
  Hash,
  Smile,
  Frown,
  Meh
} from 'lucide-react'

// Exportar todos os ícones
export {
  ChevronLeft,
  ChevronRight,
  Search,
  User,
  LogOut,
  Menu,
  X,
  Home,
  Briefcase,
  Settings,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Star,
  Heart,
  Share2,
  Edit,
  Trash2,
  Plus,
  Minus,
  Check,
  AlertCircle,
  Info,
  Filter,
  Grid,
  List,
  Eye,
  EyeOff,
  Upload,
  Download,
  ArrowLeft,
  ArrowRight,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  MessageCircle,
  Bell,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Package,
  Users,
  Building,
  Clipboard,
  FileText,
  ImageIcon,
  Camera,
  Video,
  Music,
  Scissors,
  Wrench,
  Hammer,
  PaintBucket,
  Shirt,
  Coffee,
  Pizza,
  Car,
  Bike,
  HomeIcon,
  Stethoscope,
  Dumbbell,
  Book,
  GraduationCap,
  Laptop,
  Smartphone,
  Wifi,
  Zap,
  Award,
  Target,
  TrendingUp,
  BarChart,
  PieChart,
  Bookmark,
  Flag,
  Tag,
  Percent,
  Globe,
  Link,
  Lock,
  Unlock,
  Shield,
  AlertTriangle,
  HelpCircle,
  Loader,
  RefreshCw,
  RotateCw,
  Save,
  Send,
  Copy,
  ClipboardIcon,
  Printer,
  Share,
  ThumbsUp,
  ThumbsDown,
  MessageSquare,
  AtSign,
  Hash,
  Smile,
  Frown,
  Meh
}

// Componente wrapper para facilitar o uso com props customizadas
export const Icon = ({ name, size = 24, color = "currentColor", className = "", ...props }) => {
  const icons = {
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    search: Search,
    user: User,
    logout: LogOut,
    menu: Menu,
    close: X,
    home: Home,
    briefcase: Briefcase,
    settings: Settings,
    mail: Mail,
    phone: Phone,
    mapPin: MapPin,
    calendar: Calendar,
    clock: Clock,
    star: Star,
    heart: Heart,
    share: Share2,
    edit: Edit,
    trash: Trash2,
    plus: Plus,
    minus: Minus,
    check: Check,
    alert: AlertCircle,
    info: Info,
    filter: Filter,
    grid: Grid,
    list: List,
    eye: Eye,
    eyeOff: EyeOff,
    upload: Upload,
    download: Download,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    externalLink: ExternalLink,
    message: MessageCircle,
    bell: Bell,
    cart: ShoppingCart,
    creditCard: CreditCard,
    dollar: DollarSign,
    package: Package,
    users: Users,
    building: Building,
    clipboard: Clipboard,
    file: FileText,
    image: ImageIcon,
    camera: Camera,
    video: Video,
    music: Music,
    scissors: Scissors,
    wrench: Wrench,
    hammer: Hammer,
    paint: PaintBucket,
    shirt: Shirt,
    coffee: Coffee,
    pizza: Pizza,
    car: Car,
    bike: Bike,
    health: Stethoscope,
    gym: Dumbbell,
    book: Book,
    education: GraduationCap,
    laptop: Laptop,
    smartphone: Smartphone,
    wifi: Wifi,
    zap: Zap,
    award: Award,
    target: Target,
    trending: TrendingUp,
    barChart: BarChart,
    pieChart: PieChart,
    bookmark: Bookmark,
    flag: Flag,
    tag: Tag,
    percent: Percent,
    globe: Globe,
    link: Link,
    lock: Lock,
    unlock: Unlock,
    shield: Shield,
    warning: AlertTriangle,
    help: HelpCircle,
    loader: Loader,
    refresh: RefreshCw,
    rotate: RotateCw,
    save: Save,
    send: Send,
    copy: Copy,
    printer: Printer,
    thumbsUp: ThumbsUp,
    thumbsDown: ThumbsDown,
    messageSquare: MessageSquare,
    at: AtSign,
    hash: Hash,
    smile: Smile,
    frown: Frown,
    meh: Meh
  }

  const IconComponent = icons[name]
  
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`)
    return null
  }

  return <IconComponent size={size} color={color} className={className} {...props} />
}

// Mapeamento de categorias para ícones (útil para o projeto)
export const getCategoryIcon = (categoryName) => {
  const categoryIconMap = {
    'beleza': Scissors,
    'saúde': Stethoscope,
    'educação': GraduationCap,
    'tecnologia': Laptop,
    'alimentação': Pizza,
    'transporte': Car,
    'construção': Hammer,
    'moda': Shirt,
    'fitness': Dumbbell,
    'música': Music,
    'arte': PaintBucket,
    'fotografia': Camera,
    'default': Briefcase
  }

  const normalizedName = categoryName?.toLowerCase() || ''
  const IconComponent = categoryIconMap[normalizedName] || categoryIconMap.default
  
  return IconComponent
}

// Componente para renderizar ícone de categoria com estilo
export const CategoryIcon = ({ category, size = 24, className = "" }) => {
  const IconComponent = getCategoryIcon(category?.nome)
  
  return (
    <div className={`inline-flex items-center justify-center ${className}`}>
      <IconComponent size={size} />
    </div>
  )
}

// Componente para renderizar ícone de serviço
export const ServiceIcon = ({ servico, size = 20, className = "" }) => {
  const IconComponent = getCategoryIcon(servico?.categoria || servico?.nome)
  
  return (
    <div className={`inline-flex items-center justify-center ${className}`}>
      <IconComponent size={size} />
    </div>
  )
}
